export const ALPHABET_LETTERS = [
  { letter: "A", pronunciation: "ei" },
  { letter: "B", pronunciation: "bi" },
  { letter: "C", pronunciation: "si" },
  { letter: "D", pronunciation: "di" },
  { letter: "E", pronunciation: "i" },
  { letter: "F", pronunciation: "ef" },
  { letter: "G", pronunciation: "yi" },
  { letter: "H", pronunciation: "eich" },
  { letter: "I", pronunciation: "ai" },
  { letter: "J", pronunciation: "yei" },
  { letter: "K", pronunciation: "kei" },
  { letter: "L", pronunciation: "el" },
  { letter: "M", pronunciation: "em" },
  { letter: "N", pronunciation: "en" },
  { letter: "O", pronunciation: "ou" },
  { letter: "P", pronunciation: "pi" },
  { letter: "Q", pronunciation:"kiu"},
  { letter:"R",pronunciation:"ar"},
  {letter:"S",pronunciation:"es"},
  {letter:"T",pronunciation:"ti"},
  {letter:"U",pronunciation:"iu"},
  {letter:"V",pronunciation:"vi"},
  {letter:"W",pronunciation:"dabol-iu"},
  {letter:"X",pronunciation:"exs"},
  {letter:"Y",pronunciation:"uai"},
  {letter:"Z",pronunciation:"zi"}
];